version: '3.6'

services:
  frontend:
    image: ghcr.io/joladnijo/joladnijo-webapp:latest

  backend:
    image: ghcr.io/joladnijo/joladnijo-backend:latest
    environment:
      - JWT_AUDIENCE=https://joladnijo.jmsz.hu/api/
      - JWT_KEYS=https://dev-ulmlyx6h.eu.auth0.com/.well-known/jwks.json
      - JWT_ISSUER=https://dev-ulmlyx6h.eu.auth0.com/
