version: '3.6'

services:
  frontend:
    image: ghcr.io/joladnijo/joladnijo-webapp:${IMAGE_TAG}
    container_name: joladnijo_frontend_${ENVIRONMENT}
    expose:
      - 80
    networks:
      - default
      - hosting-with-docker_nginx_reverse_proxy
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    logging:
      options:
        max-size: '1m'
        max-file: '3'

  backend:
    image: ghcr.io/joladnijo/joladnijo-backend:${IMAGE_TAG}
    container_name: joladnijo_backend_${ENVIRONMENT}
    expose:
      - 8000
    networks:
      - default
      - hosting-with-docker_nginx_reverse_proxy
    environment:
      - VIRTUAL_HOST=api.${VIRTUAL_HOST}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.${VIRTUAL_HOST}
    logging:
      options:
        max-size: '1m'
        max-file: '3'

volumes:
  database_volume: {}

networks:
  hosting-with-docker_nginx_reverse_proxy:
    external: true
  default:
    external: false
